# Site
title:              Keary Chang
bio:                'Application Java/Python Software developer with experience in networked applications. Portfolio experience with web development with focus on React and Node.js. Professional interests in pursuing full stack development. Avid biker, reader and student of life!'
description:        ""
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.JPG'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://kearychang.github.io/
#url:                http://127.0.0.1:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
future:             true

# Comments
#disqus_shortname:   kchang

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              kearychang@hotmail.com
#twitter:            username
#facebook:           username
github-url:         kearychang
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           kearychang
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
codepen:            k27chang
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
glitch:             yearofthesheep2
# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
